#include "pa_adas.h"

SharedMemory::Pool SharedMemoryPool_PA_ADAS{ "PA_ADAS", 65535 };

SharedMemory::AtomicStruct<PA_ADAS> PA_AEB_lamp(SharedMemoryPool_PA_ADAS,								"PA_AEB_lamp",							{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_FCTAleft_animation(SharedMemoryPool_PA_ADAS,						"PA_FCTAleft_animation",				{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_FCTARight_animation(SharedMemoryPool_PA_ADAS,					"PA_FCTARight_animation",				{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_FCTA_HUDwarning_Picture(SharedMemoryPool_PA_ADAS,				"PA_FCTA_HUDwarning_Picture",			{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_RCW_animation(SharedMemoryPool_PA_ADAS,							"PA_RCW_animation",						{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_RsdsSysSts_Lamp(SharedMemoryPool_PA_ADAS,						"PA_RsdsSysSts_Lamp",					{ 0, 3 });
SharedMemory::AtomicStruct<PA_ema> PA_ELOW_EmgyLane(SharedMemoryPool_PA_ADAS,							"PA_ELOW_EmgyLane",						{ 0, 0, 4 });
SharedMemory::AtomicNumber<unsigned char> PA_Callback_DPS(SharedMemoryPool_PA_ADAS,						"PA_Callback_DPS",						{ 0 });
SharedMemory::AtomicStruct<PA_ADAS> PA_TLA_Lamp(SharedMemoryPool_PA_ADAS,								"PA_TLA_Lamp",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_CC_lamp(SharedMemoryPool_PA_ADAS,								"PA_CC_lamp",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_CC_Mode(SharedMemoryPool_PA_ADAS,								"PA_CC_Mode",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_Targetbar> PA_CC_target_bar(SharedMemoryPool_PA_ADAS,						"PA_CC_target_bar",						{ 0, 0, 4 });
SharedMemory::AtomicStruct<PA_CC_Speed> PA_CC_SetSpeed(SharedMemoryPool_PA_ADAS,						"PA_CC_SetSpeed",						{ 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_speedlimt_icon> PA_First_speedlimt_icon(SharedMemoryPool_PA_ADAS,			"PA_First_speedlimt_icon",				{ 0, 0, 1, 0 });
SharedMemory::AtomicStruct<PA_speedlimt_icon> PA_Second_speedlimt_icon(SharedMemoryPool_PA_ADAS,		"PA_Second_speedlimt_icon",				{ 0, 0, 1, 0 });
SharedMemory::AtomicStruct<PA_traffic_icon> PA_First_speedlimt_supplement_icon(SharedMemoryPool_PA_ADAS,"PA_First_speedlimt_supplement_icon",	{ 0, 1 });
SharedMemory::AtomicStruct<PA_traffic_icon> PA_Traffic_sign_icon(SharedMemoryPool_PA_ADAS,				"PA_Traffic_sign_icon",					{ 0, 3 });
SharedMemory::AtomicStruct<PA_traffic_icon> PA_Camera_sign_icon(SharedMemoryPool_PA_ADAS,				"PA_Camera_sign_icon",					{ 0, 1 });
SharedMemory::AtomicNumber<unsigned char> PA_Entrance_Exit_sign_icon(SharedMemoryPool_PA_ADAS,			"PA_Entrance_Exit_sign_icon",			{ 0 });
SharedMemory::AtomicStruct<PA_tsi> PA_TSI_speed_dial_icon(SharedMemoryPool_PA_ADAS,						"PA_TSI_speed_dial_icon",				{ 0, 0, 0 });
SharedMemory::AtomicStruct<PA_adas_6bit> CPA_CtryForRoadSgnInfo(SharedMemoryPool_PA_ADAS,				"CPA_CtryForRoadSgnInfo",				{ 0, 0, 0 });
SharedMemory::AtomicStruct<PA_ADAS> PA_LCA_left_Animation(SharedMemoryPool_PA_ADAS,						"PA_LCA_left_Animation",				{ 0, 3 });
SharedMemory::AtomicStruct<PA_ADAS> PA_LCA_right_Animation(SharedMemoryPool_PA_ADAS,					"PA_LCA_right_Animation",				{ 0, 3 });
SharedMemory::AtomicStruct<PA_line> PA_LeftLine(SharedMemoryPool_PA_ADAS,								"PA_LeftLine",							{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_line> PA_LeftLine2(SharedMemoryPool_PA_ADAS,								"PA_LeftLine2",							{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_line> PA_RightLine(SharedMemoryPool_PA_ADAS,								"PA_RightLine",							{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_line> PA_RightLine2(SharedMemoryPool_PA_ADAS,								"PA_RightLine2",						{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_LKA_lamp(SharedMemoryPool_PA_ADAS,								"PA_LKA_lamp",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_ASL_lamp(SharedMemoryPool_PA_ADAS,								"PA_ASL_lamp",							{ 0, 3 });
SharedMemory::AtomicStruct<PA_ASL_Speed> PA_ASL_SetSpeed(SharedMemoryPool_PA_ADAS,						"PA_ASL_SetSpeed",						{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_ACC_lamp(SharedMemoryPool_PA_ADAS,								"PA_ACC_lamp",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_timegap> PA_ACC_Timegap(SharedMemoryPool_PA_ADAS,							"PA_ACC_Timegap",						{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_ACC_AdjustTimeGap(SharedMemoryPool_PA_ADAS,						"PA_ACC_AdjustTimeGap",					{ 0, 4 });
SharedMemory::AtomicStruct<PA_Targetbar> PS_ACC_TargetBar(SharedMemoryPool_PA_ADAS,						"PS_ACC_TargetBar",						{ 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ACC_Speed> PA_ACC_SetSpeed(SharedMemoryPool_PA_ADAS,						"PA_ACC_SetSpeed",						{ 0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_ACC_AdjustSetSpeed(SharedMemoryPool_PA_ADAS,						"PA_ACC_AdjustSetSpeed",				{ 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_ACC_FrontObj1(SharedMemoryPool_PA_ADAS,						"PA_ACC_FrontObj1",						{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_ACC_FrontObj2(SharedMemoryPool_PA_ADAS,						"PA_ACC_FrontObj2",						{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_ACC_FrntLeObj(SharedMemoryPool_PA_ADAS,						"PA_ACC_FrntLeObj",						{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_ACC_FrntRiObj(SharedMemoryPool_PA_ADAS,						"PA_ACC_FrntRiObj",						{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_override> PA_SC_Override(SharedMemoryPool_PA_ADAS,						"PA_SC_Override",						{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_GpilotStatus_Lamp(SharedMemoryPool_PA_ADAS,						"PA_GpilotStatus_Lamp",					{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_GpilotHandOff_Lamp(SharedMemoryPool_PA_ADAS,						"PA_GpilotHandOff_Lamp",				{ 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntObj1(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_FrntObj1",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntObj2(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_FrntObj2",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntLeObj(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_FrntLeObj",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntLeObj2(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_FrntLeObj2",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntRiObj(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_FrntRiObj",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_object> PA_Gpilot_FrntRiObj2(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_FrntRiObj2",					{ 0, 0.0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ramp> PA_LeftLineRamp(SharedMemoryPool_PA_ADAS,							"PA_Gpilot_FrntRiObj2",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ramp> PA_Left2LineRamp(SharedMemoryPool_PA_ADAS,							"PA_Gpilot_FrntRiObj2",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ramp> PA_RightLineRamp(SharedMemoryPool_PA_ADAS,							"PA_Gpilot_FrntRiObj2",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ramp> PA_Right2LineRamp(SharedMemoryPool_PA_ADAS,							"PA_Gpilot_FrntRiObj2",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ramp> PA_SelfLane(SharedMemoryPool_PA_ADAS,								"PA_Gpilot_FrntRiObj2",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_BoundaryWarn(SharedMemoryPool_PA_ADAS,							"PA_BoundaryWarn",						{ 0, 4 });
SharedMemory::AtomicStruct<PA_tunnel> PA_ADAS_Tunnel(SharedMemoryPool_PA_ADAS,							"PA_ADAS_Tunnel",						{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_line_animation> PA_Left_line_animation(SharedMemoryPool_PA_ADAS,			"PA_Left_line_animation",				{ 0, 0, 4 });
SharedMemory::AtomicStruct<PA_line_animation> PA_Right_line_animation(SharedMemoryPool_PA_ADAS,			"PA_Right_line_animation",				{ 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_ADAS_ODD(SharedMemoryPool_PA_ADAS,								"PA_ADAS_ODD",							{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_LaneChange(SharedMemoryPool_PA_ADAS,								"PA_LaneChange",						{ 0, 4 });
SharedMemory::AtomicStruct<PA_timegap> PA_Gpilot_TimeGap(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_TimeGap",					{ 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_Gpilot_AdjustTimeGap(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_AdjustTimeGap",				{ 0, 4 });
SharedMemory::AtomicStruct<PA_ACC_Speed> PA_Gpilot_SetSpeed(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_SetSpeed",					{ 0, 0, 0, 0, 0, 4 });
SharedMemory::AtomicStruct<PA_Targetbar> PA_Gpilot_TargetBar(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_TargetBar",					{ 0, 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_Gpilot_AdjustSetSpeed(SharedMemoryPool_PA_ADAS,					"PA_Gpilot_AdjustSetSpeed",				{ 0, 4 });
SharedMemory::AtomicStruct<PA_ADAS> PA_Gpilot_DIMLight(SharedMemoryPool_PA_ADAS,						"PA_Gpilot_DIMLight",					{ 0, 4 });
SharedMemory::AtomicStruct<PA_Menu> PA_SCFunction_Menu(SharedMemoryPool_PA_ADAS,						"PA_SCFunction_Menu",					{ 0, 0, 0, 0, 4 });
SharedMemory::AtomicNumber<unsigned char> PA_Callback_SCFunction(SharedMemoryPool_PA_ADAS,				"PA_Callback_SCFunction",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Internal_SCFunctionMode(SharedMemoryPool_PA_ADAS,			"PA_Internal_SCFunctionMode",			{ 0 });
SharedMemory::AtomicStruct<PA_config> PA_SCFunction_MenuConfig(SharedMemoryPool_PA_ADAS,				"PA_SCFunction_MenuConfig",				{ 0, 0, 0, 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Callback_AdjustMenu(SharedMemoryPool_PA_ADAS,				"PA_Callback_AdjustMenu",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_ADAS_Cursor_Position(SharedMemoryPool_PA_ADAS,				"PA_ADAS_Cursor_Position",				{ 0 });
