#include "pa_telltale.h"

SharedMemory::Pool SharedMemoryPool_PA_Telltale{ "PA_Telltale", 65535 };

SharedMemory::AtomicStruct<PA_Telltale> PA_AFSLamp(							SharedMemoryPool_PA_Telltale, "PA_AFSLamp",							{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_PositionLamp(					SharedMemoryPool_PA_Telltale, "PA_PositionLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_HighBeamLamp(					SharedMemoryPool_PA_Telltale, "PA_HighBeamLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_LowBeamLamp(						SharedMemoryPool_PA_Telltale, "PA_LowBeamLamp",						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_ABLLamp(							SharedMemoryPool_PA_Telltale, "PA_ABLLamp",							{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_ManualLevelingLamp(				SharedMemoryPool_PA_Telltale, "PA_ManualLevelingLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_FrontFogLamp(					SharedMemoryPool_PA_Telltale, "PA_FrontFogLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_RearFogLamp(						SharedMemoryPool_PA_Telltale, "PA_RearFogLamp",						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TurnLeftLamp(					SharedMemoryPool_PA_Telltale, "PA_TurnLeftLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TurnRightLamp(					SharedMemoryPool_PA_Telltale, "PA_TurnRightLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BrakeLightFailure(				SharedMemoryPool_PA_Telltale, "PA_BrakeLightFailure",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_AHBCLamp(						SharedMemoryPool_PA_Telltale, "PA_AHBCLamp",						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_ReadyLamp(					SharedMemoryPool_PA_Telltale, "PA_DIM_ReadyLamp",					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_CheckEngineLamp(				SharedMemoryPool_PA_Telltale, "PA_DIM_CheckEngineLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BATT_BatteryLowIndicator(		SharedMemoryPool_PA_Telltale, "PA_BATT_BatteryLowIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BATT_BatteryFailureIndicator(	SharedMemoryPool_PA_Telltale, "PA_BATT_BatteryFailureIndicator",	{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BATT_ChargingHandleIndicator(	SharedMemoryPool_PA_Telltale, "PA_BATT_ChargingHandleIndicator",	{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_OilPressureLamp(				SharedMemoryPool_PA_Telltale, "PA_DIM_OilPressureLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_PowerLimitationLamp(			SharedMemoryPool_PA_Telltale, "PA_DIM_PowerLimitationLamp",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_SystemFaultLamp(				SharedMemoryPool_PA_Telltale, "PA_DIM_SystemFaultLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_ElectricalMachineErrorLamp(	SharedMemoryPool_PA_Telltale, "PA_DIM_ElectricalMachineErrorLamp",  { 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_SRSLamp(						SharedMemoryPool_PA_Telltale, "PA_DIM_SRSLamp",						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_ESCIndicator(				SharedMemoryPool_PA_Telltale, "PA_BRK_ESCIndicator",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_EscSportIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_EscSportIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_ABSIndicator(				SharedMemoryPool_PA_Telltale, "PA_BRK_ABSIndicator",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_HDCWhiteIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_HDCWhiteIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_HDCGreenIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_HDCGreenIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_HDCYellowIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_HDCYellowIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_BrakeReleaseIndicator(		SharedMemoryPool_PA_Telltale, "PA_BRK_BrakeReleaseIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_EPBIndicator(				SharedMemoryPool_PA_Telltale, "PA_BRK_EPBIndicator",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_BrakeYellowIndicator(		SharedMemoryPool_PA_Telltale, "PA_BRK_BrakeYellowIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_BrakeRedIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_BrakeRedIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_BRK_AutoHoldIndicator(			SharedMemoryPool_PA_Telltale, "PA_BRK_AutoHoldIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_EngineCoolantWarningLamp(	SharedMemoryPool_PA_Telltale, "PA_DIM_EngineCoolantWarningLamp",	{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TowbarUnlockLamp(				SharedMemoryPool_PA_Telltale, "PA_TowbarUnlockLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TrailerLightStatusLamp(			SharedMemoryPool_PA_Telltale, "PA_TrailerLightStatusLamp",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TrailerServiceLamp(				SharedMemoryPool_PA_Telltale, "PA_TrailerServiceLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_StartStopLamp(				SharedMemoryPool_PA_Telltale, "PA_DIM_StartStopLamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_LVE_BatteryIndicator(			SharedMemoryPool_PA_Telltale, "PA_LVE_BatteryIndicator",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_LeftChildLockStatus(			SharedMemoryPool_PA_Telltale, "PA_DIM_LeftChildLockStatus",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_RightChildLockStatus(		SharedMemoryPool_PA_Telltale, "PA_DIM_RightChildLockStatus",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SteeringIndicator(				SharedMemoryPool_PA_Telltale, "PA_SteeringIndicator",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TIR_TirePressureFault(			SharedMemoryPool_PA_Telltale, "PA_TIR_TirePressureFault",			{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionYellowIndicator(	SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionYellowIndicator",  { 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionRedIndicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionRedIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionMovingUpIndicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionMovingUpIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionMovingDownIndicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionMovingDownIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionStopIndicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionStopIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionCurrentLevelLL1Indicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionCurrentLevelLL1Indicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionCurrentLevelLL2Indicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionCurrentLevelLL2Indicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionCurrentLevelNRHIndicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionCurrentLevelNRHIndicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionCurrentLevelHL1Indicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionCurrentLevelHL1Indicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SUSP_SuspensionCurrentLevelHL2Indicator(		SharedMemoryPool_PA_Telltale, "PA_SUSP_SuspensionCurrentLevelHL2Indicator",		{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DPS_coffeecup_lamp(				SharedMemoryPool_PA_Telltale, "PA_DPS_coffeecup_lamp",				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_ExternalArtIficialSoundLamp(	SharedMemoryPool_PA_Telltale, "PA_DIM_ExternalArtIficialSoundLamp", { 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_DIM_ParkingEmergencyBrakeLamp(	SharedMemoryPool_PA_Telltale, "PA_DIM_ParkingEmergencyBrakeLamp",	{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_EPWISt(							SharedMemoryPool_PA_Telltale, "PA_EPWISt", 							{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_EPWIStUS(						SharedMemoryPool_PA_Telltale, "PA_EPWIStUS", 						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_RWSIndicator(					SharedMemoryPool_PA_Telltale, "PA_RWSIndicator", 					{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_EpedalIndicator(					SharedMemoryPool_PA_Telltale, "PA_EpedalIndicator", 				{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_Seatbelt(						SharedMemoryPool_PA_Telltale, "PA_Seatbelt",						{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_SVSLamp(							SharedMemoryPool_PA_Telltale, "PA_SVSLamp",							{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_TCMLamp(							SharedMemoryPool_PA_Telltale, "PA_TCMLamp",							{ 4,0 });
SharedMemory::AtomicStruct<PA_Telltale> PA_OLI_OilLevelIndicated(			SharedMemoryPool_PA_Telltale, "PA_OLI_OilLevelIndicated",			{ 4,0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_Driver(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_Driver",					{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_Passenger(			SharedMemoryPool_PA_Telltale, "PA_Seatbelt_Passenger",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_MidPassenger(			SharedMemoryPool_PA_Telltale, "PA_Seatbelt_MidPassenger",			{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_SecLeft(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_SecLeft",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_SecMid(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_SecMid",					{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_SecRight(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_SecRight",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_ThrdLeft(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_ThrdLeft",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_ThrdMid(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_ThrdMid",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_ThrdRight(			SharedMemoryPool_PA_Telltale, "PA_Seatbelt_ThrdRight",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_FrthLeft(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_FrthLeft",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_FrthMid(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_FrthMid",				{ 0 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_FrthRight(			SharedMemoryPool_PA_Telltale, "PA_Seatbelt_FrthRight",				{ 0 });


SharedMemory::AtomicStruct<PA_Telltale> CPA_UsgModSts(						SharedMemoryPool_PA_Telltale, "CPA_UsgModSts", 						{ 4,0 });
SharedMemory::AtomicNumber<unsigned char> CPA_Carconfig8(					SharedMemoryPool_PA_Telltale, "CPA_Carconfig8", 					{ 1 });
SharedMemory::AtomicNumber<unsigned char> PA_Seatbelt_output(				SharedMemoryPool_PA_Telltale, "PA_Seatbelt_output", 				{ 0 });
